minigames:
  TNT_RUN:
    display_name: "§cTNT Run"
    icon: "TNT"
    lore:
      - "§7Run over the TNT platform."
      - "§7Last one standing wins!"
    enabled_modes:
      - CLASSIC
      - HARDCORE
      - TIMED

  BED_WARS:
    display_name: "§bBed Wars"
    icon: "BEDROCK"
    lore:
      - "§7Protect your bed, destroy others."
      - "§7Team up or go solo!"
    enabled_modes:
      - SOLO
      - TEAMS
      - HARDCORE

  SKY_WARS:
    display_name: "§eSky Wars"
    icon: "ENDER_PEARL"
    lore:
      - "§7Battle on floating islands."
      - "§7Gather loot, be last alive!"
    enabled_modes:
      - SOLO
      - TEAMS
      - INSANE

  SPLEEF:
    display_name: "§dSpleef"
    icon: "DIAMOND_SHOVEL"
    lore:
      - "§7Break blocks beneath opponents."
      - "§7Last man standing wins!"
    enabled_modes:
      - CLASSIC
      - TEAM

  # ... add more minigames here ...